(()=>{
'use strict';
const D=window.UAX_DATA;
const $=(s,e=document)=>e.querySelector(s), $$=(s,e=document)=>[...e.querySelectorAll(s)];
const LS='uaxBioProgressV3', OLD_KEYS=['uaxBioProgressV2','uaxBioProgressV1'];
let timerHandle=null;

const GLOSSARY={
'eau':'agua','sel minéral':'sal mineral','sels minéraux':'sales minerales','glucide':'glúcido','glucides':'glúcidos','lipide':'lípido','lipides':'lípidos','protéine':'proteína','protéines':'proteínas','acide aminé':'aminoácido','enzyme':'enzima','substrat':'sustrato','adn':'ADN','arn':'ARN','arnm':'ARNm','atp':'ATP','respiration':'respiración','fermentation':'fermentación','diffusion':'difusión','osmose':'ósmosis','membrane plasmique':'membrana plasmática','cellule':'célula','noyau':'núcleo','mitochondrie':'mitocondria','ribosome':'ribosoma','lysosome':'lisosoma','appareil de golgi':'aparato de Golgi','réticulum endoplasmique':'retículo endoplasmático','chloroplaste':'cloroplasto','cytoplasme':'citoplasma','procaryote':'procariota','eucaryote':'eucariota','chromosome':'cromosoma','chromatide':'cromátida','gène':'gen','allèle':'alelo','mutation':'mutación','réplication':'replicación','transcription':'transcripción','traduction':'traducción','mitose':'mitosis','méiose':'meiosis','gamète':'gameto','génotype':'genotipo','phénotype':'fenotipo','tissu':'tejido','épithélium':'epitelio','tissu conjonctif':'tejido conjuntivo','tissu adipeux':'tejido adiposo','cartilage':'cartílago','tissu osseux':'tejido óseo','muscle':'músculo','tissu nerveux':'tejido nervioso','sang':'sangre','digestion':'digestión','respiration pulmonaire':'respiración pulmonar','circulation':'circulación','excrétion':'excreción','reproduction':'reproducción','neurone':'neurona','synapse':'sinapsis','glycémie':'glucemia','insuline':'insulina','glucagon':'glucagón','bactérie':'bacteria','archée':'arquea','virus':'virus','plasmide':'plásmido','antibiotique':'antibiótico','antibiogramme':'antibiograma','conjugaison':'conjugación','transformation':'transformación','transduction':'transducción','anticorps':'anticuerpo','antigène':'antígeno','lymphocyte':'linfocito','phagocytose':'fagocitosis','immunité innée':'inmunidad innata','immunité adaptative':'inmunidad adaptativa','vaccination':'vacunación','mémoire immunitaire':'memoria inmunitaria','sélection naturelle':'selección natural','dérive génétique':'deriva genética','flux génique':'flujo génico','spéciation':'especiación','adaptation':'adaptación','biodiversité':'biodiversidad','espèce':'especie','population':'población','écosystème':'ecosistema','phylogénie':'filogenia','arbre phylogénétique':'árbol filogenético','clade':'clado','domaine':'dominio','taxonomie':'taxonomía'
};
const STOP=new Set('avec sans dans pour par sur sous entre chez vers plus moins cette ces une un des les la le de du d au aux en et ou est sont être avoir qui que quoi quel quelle quels quelles comment pourquoi quand où leur leurs son sa ses ce se ne pas peut peuvent principal principalement fonction structure niveau organisme organite processus réponse'.split(/\s+/));

const VISUAL_QS=[
{cid:1,id:'v1',difficulty:2,q:'Quel élément du schéma forme la barrière principale de la membrane plasmique ?',qEs:'¿Qué elemento del esquema forma la barrera principal de la membrana plasmática?',options:[['A','Une bicouche de phospholipides'],['B','Une couche de glycogène'],['C','Une double couche de protéines'],['D','Une couche d’ADN']],optionsEs:[['A','Una bicapa de fosfolípidos'],['B','Una capa de glucógeno'],['C','Una doble capa de proteínas'],['D','Una capa de ADN']],answer:'A',why:'Les phospholipides s’organisent en bicouche : têtes hydrophiles vers l’eau et queues hydrophobes au centre.',whyEs:'Los fosfolípidos forman una bicapa: cabezas hidrófilas hacia el agua y colas hidrófobas hacia el centro.',svg:`<svg viewBox="0 0 520 190" role="img" aria-label="Schéma simplifié d'une bicouche de phospholipides"><rect width="520" height="190" rx="18" fill="#eef4ff"/><g stroke="#3769e8" stroke-width="3"><g fill="#fff"><circle cx="60" cy="50" r="11"/><circle cx="105" cy="50" r="11"/><circle cx="150" cy="50" r="11"/><circle cx="195" cy="50" r="11"/><circle cx="240" cy="50" r="11"/><circle cx="285" cy="50" r="11"/><circle cx="330" cy="50" r="11"/><circle cx="375" cy="50" r="11"/><circle cx="420" cy="50" r="11"/><circle cx="465" cy="50" r="11"/><circle cx="60" cy="140" r="11"/><circle cx="105" cy="140" r="11"/><circle cx="150" cy="140" r="11"/><circle cx="195" cy="140" r="11"/><circle cx="240" cy="140" r="11"/><circle cx="285" cy="140" r="11"/><circle cx="330" cy="140" r="11"/><circle cx="375" cy="140" r="11"/><circle cx="420" cy="140" r="11"/><circle cx="465" cy="140" r="11"/></g><g><path d="M55 61l-8 52M65 61l8 52M100 61l-8 52M110 61l8 52M145 61l-8 52M155 61l8 52M190 61l-8 52M200 61l8 52M235 61l-8 52M245 61l8 52M280 61l-8 52M290 61l8 52M325 61l-8 52M335 61l8 52M370 61l-8 52M380 61l8 52M415 61l-8 52M425 61l8 52M460 61l-8 52M470 61l8 52"/></g></g><text x="260" y="24" text-anchor="middle" font-size="15" fill="#31405f">Milieu extracellulaire</text><text x="260" y="180" text-anchor="middle" font-size="15" fill="#31405f">Cytoplasme</text></svg>`},
{cid:2,id:'v2',difficulty:1,q:'La flèche désigne un organite à double membrane possédant des crêtes internes. Lequel ?',qEs:'La flecha señala un orgánulo de doble membrana con crestas internas. ¿Cuál es?',options:[['A','Lysosome'],['B','Mitochondrie'],['C','Ribosome'],['D','Appareil de Golgi']],optionsEs:[['A','Lisosoma'],['B','Mitocondria'],['C','Ribosoma'],['D','Aparato de Golgi']],answer:'B',why:'La mitochondrie possède une double membrane et une membrane interne repliée en crêtes.',whyEs:'La mitocondria posee una doble membrana y una membrana interna plegada en crestas.',svg:`<svg viewBox="0 0 520 220" role="img" aria-label="Cellule simplifiée avec une mitochondrie indiquée par une flèche"><rect width="520" height="220" rx="20" fill="#f5f8ff"/><ellipse cx="250" cy="112" rx="205" ry="82" fill="#e8f2ef" stroke="#5b8194" stroke-width="3"/><circle cx="210" cy="110" r="45" fill="#cfdcff" stroke="#6078aa" stroke-width="3"/><ellipse cx="350" cy="120" rx="48" ry="25" fill="#ffd9b8" stroke="#c87837" stroke-width="3"/><path d="M315 120c12-24 22 24 34 0s22 24 38 0" fill="none" stroke="#c87837" stroke-width="3"/><path d="M455 50L390 92" stroke="#c4434a" stroke-width="5"/><path d="M390 92l10-2-4 10z" fill="#c4434a"/><text x="460" y="42" text-anchor="end" font-size="16" fill="#8a3340">?</text></svg>`},
{cid:3,id:'v3',difficulty:2,q:'Deux compartiments sont séparés par une membrane perméable à l’eau mais pas au soluté. Vers quel côté l’eau se déplace-t-elle majoritairement ?',qEs:'Dos compartimentos están separados por una membrana permeable al agua pero no al soluto. ¿Hacia qué lado se desplaza principalmente el agua?',options:[['A','Vers le côté le moins concentré en soluté'],['B','Vers le côté le plus concentré en soluté'],['C','Elle ne se déplace jamais'],['D','Uniquement si de l’ATP est fourni']],optionsEs:[['A','Hacia el lado menos concentrado en soluto'],['B','Hacia el lado más concentrado en soluto'],['C','Nunca se desplaza'],['D','Solo si se aporta ATP']],answer:'B',why:'Par osmose, l’eau se déplace globalement vers le compartiment où la concentration en solutés non diffusibles est la plus élevée.',whyEs:'Por ósmosis, el agua se desplaza globalmente hacia el compartimento con mayor concentración de solutos no difusibles.',svg:`<svg viewBox="0 0 520 220" role="img" aria-label="Deux compartiments séparés par une membrane avec des concentrations différentes"><rect width="520" height="220" rx="18" fill="#f4f8ff"/><rect x="45" y="40" width="190" height="140" rx="10" fill="#dff2ff" stroke="#5e87a0" stroke-width="3"/><rect x="285" y="40" width="190" height="140" rx="10" fill="#dff2ff" stroke="#5e87a0" stroke-width="3"/><line x1="260" y1="30" x2="260" y2="190" stroke="#59647a" stroke-width="5" stroke-dasharray="8 7"/><g fill="#714ee8"><circle cx="95" cy="95" r="8"/><circle cx="170" cy="135" r="8"/><circle cx="325" cy="75" r="8"/><circle cx="365" cy="105" r="8"/><circle cx="415" cy="70" r="8"/><circle cx="330" cy="145" r="8"/><circle cx="395" cy="150" r="8"/><circle cx="445" cy="120" r="8"/></g><path d="M205 205h105" stroke="#3769e8" stroke-width="6"/><path d="M310 205l-15-9v18z" fill="#3769e8"/><text x="140" y="25" text-anchor="middle" fill="#31405f">peu de soluté</text><text x="380" y="25" text-anchor="middle" fill="#31405f">beaucoup de soluté</text></svg>`},
{cid:4,id:'v4',difficulty:2,q:'La structure en X représentée correspond à un chromosome après réplication. Combien de chromatides contient-elle ?',qEs:'La estructura en X representa un cromosoma después de la replicación. ¿Cuántas cromátidas contiene?',options:[['A','Une'],['B','Deux'],['C','Quatre'],['D','Huit']],optionsEs:[['A','Una'],['B','Dos'],['C','Cuatro'],['D','Ocho']],answer:'B',why:'Après réplication et avant séparation, un chromosome est constitué de deux chromatides sœurs reliées au centromère.',whyEs:'Después de la replicación y antes de la separación, un cromosoma está formado por dos cromátidas hermanas unidas por el centrómero.',svg:`<svg viewBox="0 0 520 220" role="img" aria-label="Chromosome en X avec deux chromatides sœurs"><rect width="520" height="220" rx="18" fill="#f6f4ff"/><path d="M175 35c45 30 55 65 85 75-30 15-45 50-80 78" fill="none" stroke="#714ee8" stroke-width="24" stroke-linecap="round"/><path d="M345 35c-45 30-55 65-85 75 30 15 45 50 80 78" fill="none" stroke="#3769e8" stroke-width="24" stroke-linecap="round"/><circle cx="260" cy="110" r="12" fill="#f2a444"/><text x="260" y="210" text-anchor="middle" font-size="15" fill="#53617b">centromère</text></svg>`},
{cid:5,id:'v5',difficulty:2,q:'Quel type de tissu est schématisé par des cellules très jointives reposant sur une membrane basale ?',qEs:'¿Qué tipo de tejido está representado por células muy juntas apoyadas sobre una membrana basal?',options:[['A','Tissu épithélial'],['B','Tissu adipeux'],['C','Tissu osseux'],['D','Tissu musculaire']],optionsEs:[['A','Tejido epitelial'],['B','Tejido adiposo'],['C','Tejido óseo'],['D','Tejido muscular']],answer:'A',why:'Un épithélium est constitué de cellules étroitement jointives, avec peu de matrice extracellulaire, reposant sur une lame basale.',whyEs:'Un epitelio está formado por células muy unidas, con poca matriz extracelular, apoyadas sobre una lámina basal.',svg:`<svg viewBox="0 0 520 210" role="img" aria-label="Couche de cellules épithéliales reposant sur une membrane basale"><rect width="520" height="210" rx="18" fill="#fff8f5"/><g fill="#ffd6d6" stroke="#aa6670" stroke-width="2"><rect x="55" y="55" width="65" height="80" rx="12"/><rect x="122" y="55" width="65" height="80" rx="12"/><rect x="189" y="55" width="65" height="80" rx="12"/><rect x="256" y="55" width="65" height="80" rx="12"/><rect x="323" y="55" width="65" height="80" rx="12"/><rect x="390" y="55" width="65" height="80" rx="12"/></g><g fill="#845f8f"><circle cx="87" cy="95" r="9"/><circle cx="154" cy="95" r="9"/><circle cx="221" cy="95" r="9"/><circle cx="288" cy="95" r="9"/><circle cx="355" cy="95" r="9"/><circle cx="422" cy="95" r="9"/></g><line x1="45" y1="145" x2="465" y2="145" stroke="#3769e8" stroke-width="6"/><text x="260" y="175" text-anchor="middle" fill="#53617b">membrane basale</text></svg>`},
{cid:6,id:'v6',difficulty:2,q:'Dans le schéma simplifié, quel circuit conduit le sang du cœur vers les poumons puis au cœur ?',qEs:'En el esquema simplificado, ¿qué circuito lleva la sangre del corazón a los pulmones y de vuelta al corazón?',options:[['A','La circulation pulmonaire'],['B','La circulation systémique'],['C','La circulation lymphatique'],['D','La circulation porte uniquement']],optionsEs:[['A','La circulación pulmonar'],['B','La circulación sistémica'],['C','La circulación linfática'],['D','Solo la circulación portal']],answer:'A',why:'La petite circulation ou circulation pulmonaire relie le cœur aux poumons pour les échanges gazeux.',whyEs:'La circulación pulmonar conecta el corazón con los pulmones para realizar los intercambios gaseosos.',svg:`<svg viewBox="0 0 520 230" role="img" aria-label="Schéma cœur poumons organisme"><rect width="520" height="230" rx="18" fill="#f6f9ff"/><ellipse cx="260" cy="125" rx="45" ry="52" fill="#f1a4aa" stroke="#a44c55" stroke-width="3"/><ellipse cx="120" cy="80" rx="65" ry="38" fill="#cde8ff" stroke="#5c85a3" stroke-width="3"/><ellipse cx="400" cy="80" rx="65" ry="38" fill="#cde8ff" stroke="#5c85a3" stroke-width="3"/><path d="M220 105C185 75 175 70 160 72M300 105c35-30 45-35 60-33" fill="none" stroke="#3769e8" stroke-width="7"/><path d="M160 92c25 40 45 45 65 55M360 92c-25 40-45 45-65 55" fill="none" stroke="#c4434a" stroke-width="7"/><text x="120" y="30" text-anchor="middle" fill="#53617b">poumon</text><text x="400" y="30" text-anchor="middle" fill="#53617b">poumon</text><text x="260" y="205" text-anchor="middle" fill="#53617b">cœur</text></svg>`},
{cid:7,id:'v7',difficulty:2,q:'Le schéma montre une cellule sans noyau avec un chromosome circulaire et des plasmides. Quel organisme correspond le mieux ?',qEs:'El esquema muestra una célula sin núcleo con un cromosoma circular y plásmidos. ¿Qué organismo corresponde mejor?',options:[['A','Une bactérie'],['B','Une cellule animale'],['C','Un virus'],['D','Un neurone']],optionsEs:[['A','Una bacteria'],['B','Una célula animal'],['C','Un virus'],['D','Una neurona']],answer:'A',why:'Une bactérie est une cellule procaryote : pas de noyau, ADN principal circulaire et plasmides possibles.',whyEs:'Una bacteria es una célula procariota: no tiene núcleo, posee ADN circular principal y puede contener plásmidos.',svg:`<svg viewBox="0 0 520 220" role="img" aria-label="Bactérie simplifiée avec ADN circulaire et plasmides"><rect width="520" height="220" rx="18" fill="#f3fbf6"/><rect x="85" y="48" width="350" height="125" rx="62" fill="#d9f1df" stroke="#548266" stroke-width="4"/><path d="M180 110c30-50 90 50 145 0s70 35 25 43c-55 10-95-55-145-12" fill="none" stroke="#714ee8" stroke-width="5"/><circle cx="355" cy="92" r="18" fill="none" stroke="#3769e8" stroke-width="4"/><circle cx="155" cy="82" r="12" fill="none" stroke="#3769e8" stroke-width="4"/><g fill="#4f735d"><circle cx="130" cy="130" r="4"/><circle cx="390" cy="130" r="4"/><circle cx="320" cy="75" r="4"/><circle cx="220" cy="75" r="4"/></g><path d="M435 110c45 0 35 55 75 55" fill="none" stroke="#548266" stroke-width="4"/></svg>`},
{cid:8,id:'v8',difficulty:2,q:'La structure en Y représentée reconnaît spécifiquement un antigène. De quelle molécule s’agit-il ?',qEs:'La estructura en Y representada reconoce específicamente un antígeno. ¿De qué molécula se trata?',options:[['A','Un anticorps'],['B','Une cytokine'],['C','Une enzyme digestive'],['D','Une molécule d’ATP']],optionsEs:[['A','Un anticuerpo'],['B','Una citocina'],['C','Una enzima digestiva'],['D','Una molécula de ATP']],answer:'A',why:'Les anticorps sont des immunoglobulines en forme de Y dont les extrémités portent des sites de liaison spécifiques à l’antigène.',whyEs:'Los anticuerpos son inmunoglobulinas en forma de Y cuyas extremidades contienen sitios de unión específicos para el antígeno.',svg:`<svg viewBox="0 0 520 220" role="img" aria-label="Anticorps en forme de Y et antigènes"><rect width="520" height="220" rx="18" fill="#f7f5ff"/><path d="M260 180V110M260 112L190 45M260 112l70-67" fill="none" stroke="#714ee8" stroke-width="18" stroke-linecap="round"/><circle cx="178" cy="35" r="14" fill="#f2a444"/><circle cx="342" cy="35" r="14" fill="#f2a444"/><text x="260" y="207" text-anchor="middle" fill="#53617b">molécule en Y</text></svg>`},
{cid:9,id:'v9',difficulty:3,q:'Dans cet exemple, une population subit un événement aléatoire qui réduit fortement ses effectifs. Quel mécanisme peut alors modifier rapidement les fréquences alléliques ?',qEs:'En este ejemplo, una población sufre un acontecimiento aleatorio que reduce mucho su tamaño. ¿Qué mecanismo puede modificar rápidamente las frecuencias alélicas?',options:[['A','La dérive génétique'],['B','La traduction'],['C','La mitose'],['D','La vaccination']],optionsEs:[['A','La deriva genética'],['B','La traducción'],['C','La mitosis'],['D','La vacunación']],answer:'A',why:'Dans une petite population, le hasard peut fortement modifier les fréquences alléliques : c’est la dérive génétique, particulièrement marquée après un goulot d’étranglement.',whyEs:'En una población pequeña, el azar puede modificar mucho las frecuencias alélicas: es la deriva genética, especialmente tras un cuello de botella.',svg:`<svg viewBox="0 0 520 220" role="img" aria-label="Population nombreuse puis goulot d'étranglement puis petite population"><rect width="520" height="220" rx="18" fill="#f8f9ff"/><g fill="#3769e8">${Array.from({length:18},(_,i)=>`<circle cx="${55+(i%6)*28}" cy="${55+Math.floor(i/6)*28}" r="9"/>`).join('')}</g><path d="M245 45l50 65-50 65" fill="#e6eaf4" stroke="#8793aa" stroke-width="3"/><g fill="#714ee8"><circle cx="355" cy="85" r="10"/><circle cx="390" cy="115" r="10"/><circle cx="425" cy="80" r="10"/><circle cx="445" cy="135" r="10"/><circle cx="365" cy="150" r="10"/></g><text x="140" y="190" text-anchor="middle" fill="#53617b">population initiale</text><text x="400" y="190" text-anchor="middle" fill="#53617b">population réduite</text></svg>`},
{cid:10,id:'v10',difficulty:3,q:'Sur cet arbre simplifié, quelles espèces partagent l’ancêtre commun le plus récent ?',qEs:'En este árbol simplificado, ¿qué especies comparten el ancestro común más reciente?',options:[['A','A et B'],['B','B et C'],['C','C et D'],['D','A et D']],optionsEs:[['A','A y B'],['B','B y C'],['C','C y D'],['D','A y D']],answer:'C',why:'C et D se rejoignent au nœud le plus proche des extrémités : ils partagent donc l’ancêtre commun le plus récent parmi les propositions.',whyEs:'C y D se unen en el nodo más cercano a las puntas; por tanto comparten el ancestro común más reciente entre las opciones.',svg:`<svg viewBox="0 0 520 230" role="img" aria-label="Arbre phylogénétique simplifié avec espèces A B C D"><rect width="520" height="230" rx="18" fill="#f5faf7"/><g stroke="#416c56" stroke-width="5" fill="none"><path d="M90 190V55M90 140h90M180 140V85M180 110h90M270 110V65M270 85h100M370 85V45M370 85v55"/></g><g font-size="18" fill="#263858"><text x="385" y="50">C</text><text x="385" y="148">D</text><text x="285" y="70">B</text><text x="195" y="92">A</text></g></svg>`}
];

function blank(){return {version:'3.1',checks:{},flash:{},quiz:{},qAttempts:{},errors:{},lastChapter:1,examHistory:[],examActive:null,examLast:null,practiceActive:null,practiceLast:null,activity:[],plan:{},settings:{lang:'fr',dark:false,targetDate:'2026-12-15',dailyNewCards:12}};}
function load(){
  let obj={};
  try{let raw=localStorage.getItem(LS);if(!raw){for(const k of OLD_KEYS){raw=localStorage.getItem(k);if(raw)break}}obj=raw?JSON.parse(raw):{};}catch(e){obj={};}
  let out=Object.assign(blank(),obj);out.settings=Object.assign(blank().settings,obj.settings||{});out.qAttempts=obj.qAttempts||{};out.plan=obj.plan||{};out.activity=obj.activity||[];out.version='3.1';if(out.examActive&&!out.examActive.orders)out.examActive.orders={};if(out.practiceActive&&!out.practiceActive.orders)out.practiceActive.orders={};
  for(const [k,v] of Object.entries(out.flash||{})){if(v&&v.level!=null&&v.due==null){const lvl=+v.level||0,days=[0,1,3,7][lvl]||0;out.flash[k]=Object.assign({},v,{strength:[0,35,65,85][lvl]||0,interval:days,reps:lvl?1:0,due:(v.date||Date.now())+days*86400000,lastRating:lvl});}}
  return out;
}
let state=load();
const qp=new URLSearchParams(location.search);
let view={type:qp.get('view')||'dashboard',chapter:1,tab:'course',fcIndex:0,fcFlip:false,qIndex:0,qAnswered:false,qDifficulty:'all',examCount:30,planMode:'today',searchQuery:'',highlight:'',reviewRefs:[],reviewIndex:0,reviewFlip:false};
function save(){state.version='3.1';localStorage.setItem(LS,JSON.stringify(state));}
function logActivity(type,meta={}){state.activity.unshift({t:Date.now(),type,...meta});state.activity=state.activity.slice(0,500);save();}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function chapter(id){return D.find(x=>x.id===+id);}
function stripHtml(s){let d=document.createElement('div');d.innerHTML=s||'';return d.textContent||'';}
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9à-ÿ ]/gi,' ');}
function tokens(s){return [...new Set(norm(s).split(/\s+/).filter(x=>x.length>=4&&!STOP.has(x)))];}
function looksSpanish(s){return /[¿¡]|\b(qué|cuál|dónde|cómo|tejido|célula|anticuerpo|biodiversidad|selección|flujo|membrana|mitocondria|bacteria|inmunidad|cromosoma|glucemia)\b/i.test(s||'');}
function visualFor(cid){return VISUAL_QS.filter(q=>q.cid===+cid);}
function qid(q){return String(q.id);}
function fullQuestions(c){return [...c.qcm.map(q=>Object.assign({_source:'base'},q)),...visualFor(c.id).map(q=>Object.assign({_source:'visual'},q))];}
function getRef(ref){let c=chapter(ref.cid);let q=ref.source==='visual'?visualFor(ref.cid).find(x=>x.id===ref.qid):c.qcm.find(x=>String(x.id)===String(ref.qid));return {c,q};}
function makeRef(cid,q){return {cid:+cid,qid:String(q.id),source:q._source||('svg'in q?'visual':'base')};}
function questionText(q){return state.settings.lang==='es'&&q.qEs?q.qEs:q.q;}
function questionWhy(q){return state.settings.lang==='es'&&q.whyEs?q.whyEs:q.why;}
function questionOptions(q){if(state.settings.lang==='es'&&q.optionsEs)return q.optionsEs.map(([key,text])=>({key,text}));return (q.options||[]).map(o=>Array.isArray(o)?{key:o[0],text:o[1]}:o);}
function glossaryHints(text,max=6){let low=norm(text),hits=[];for(const [fr,es] of Object.entries(GLOSSARY)){if(low.includes(norm(fr))&&!hits.some(x=>x[1]===es))hits.push([fr,es]);if(hits.length>=max)break;}return hits;}
function vocabHtml(text,max=6){if(state.settings.lang==='fr')return '';let h=glossaryHints(text,max);return h.length?`<div class="vocab-hints" aria-label="Vocabulaire espagnol">${h.map(([a,b])=>`<span><b>${esc(a)}</b> → ${esc(b)}</span>`).join('')}</div>`:'';}
function fmtDate(d,long=false){return new Intl.DateTimeFormat('fr-FR',long?{weekday:'long',day:'numeric',month:'long'}:{day:'2-digit',month:'2-digit'}).format(d);}
function isoDate(d){let y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`;}
function dateFromIso(s){let [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d,12,0,0);}
function addDays(d,n){let x=new Date(d);x.setDate(x.getDate()+n);return x;}
function daysBetween(a,b){return Math.floor((dateFromIso(b)-dateFromIso(a))/86400000);}
function todayIso(){return isoDate(new Date());}
function formatTime(ms){let s=Math.max(0,Math.ceil(ms/1000)),m=Math.floor(s/60);return `${String(m).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function hash(s){let h=2166136261;for(const ch of String(s)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
function seededOrder(q,seed){let keys=questionOptions(q).map(x=>x.key),h=hash(seed);for(let i=keys.length-1;i>0;i--){h=(Math.imul(h,1664525)+1013904223)>>>0;let j=h%(i+1);[keys[i],keys[j]]=[keys[j],keys[i]];}return keys;}
function answerText(q,key){return questionOptions(q).find(x=>x.key===key)?.text||key;}
function displayOptions(q,order,attr,selected=null,disabled=false){let map=new Map(questionOptions(q).map(x=>[x.key,x.text]));return order.map((orig,i)=>`<button class="answer ${selected===orig?'selected':''}" ${disabled?'disabled':''} ${attr}="${esc(orig)}" data-shortcut="${String.fromCharCode(65+i)}" aria-label="Réponse ${String.fromCharCode(65+i)} : ${esc(map.get(orig)||'')}"><b>${String.fromCharCode(65+i)}.</b> <span>${esc(map.get(orig)||'')}</span></button>`).join('');}
function difficulty(c,q){if(q.difficulty)return q.difficulty;let idx=c.qcm.findIndex(x=>String(x.id)===String(q.id));if(idx<0)return 2;if(idx<13)return 1;if(idx<30)return 2;return 3;}
const DIFF_LABEL={1:'Fondamental',2:'Standard',3:'Approfondi'};
function poolForChapter(c){let p=fullQuestions(c);if(state.settings.lang==='es')p=p.filter(q=>q.qEs||looksSpanish(q.q));if(view.qDifficulty!=='all')p=p.filter(q=>difficulty(c,q)===+view.qDifficulty);return p.length?p:fullQuestions(c);}

function flashStrength(st){return Math.max(0,Math.min(100,st?.strength??([0,35,65,85][st?.level||0]||0)));}
function dueFlashRefs(limit=30,scope=null){let now=Date.now(),due=[],fresh=[];let chapters=scope?.length?scope.map(chapter):D;for(const c of chapters){for(const f of c.flashcards){let k=c.id+'-'+f.id,st=state.flash[k];if(st?.due&&st.due<=now)due.push({cid:c.id,fid:f.id,due:st.due});else if(!st)fresh.push({cid:c.id,fid:f.id,due:Infinity});}}due.sort((a,b)=>a.due-b.due);let capNew=Math.max(0,state.settings.dailyNewCards||12);let weak=chapters.sort((a,b)=>chStats(a).p-chStats(b).p).map(x=>x.id);fresh.sort((a,b)=>weak.indexOf(a.cid)-weak.indexOf(b.cid));return [...due,...fresh.slice(0,capNew)].slice(0,limit);}
function rateFlash(cid,fid,rating){let k=cid+'-'+fid,old=state.flash[k]||{interval:0,reps:0,strength:0};let interval=old.interval||0,strength=flashStrength(old),reps=old.reps||0;if(rating===0){interval=10/(60*24);reps=0;strength=Math.max(5,strength-18);}else if(rating===1){interval=Math.max(1,interval?interval*1.25:1);reps++;strength=Math.min(100,strength+4);}else if(rating===2){interval=reps?Math.max(2,interval*2.2):2;reps++;strength=Math.min(100,strength+14);}else{interval=reps?Math.max(4,interval*3.2):4;reps++;strength=Math.min(100,strength+23);}state.flash[k]={due:Date.now()+interval*86400000,interval,reps,strength,lastRating:rating,date:Date.now()};logActivity('flash',{cid,rating});}
function relatedScore(a,b){let ta=tokens(a),tb=new Set(tokens(b));if(!ta.length)return 0;return ta.filter(x=>tb.has(x)).length/Math.min(4,ta.length);}
function notionMastery(c,i){
  let e=c.essentials[i],checked=state.checks[c.id+'-'+i]?1:0;
  let fr=c.flashcards.filter(f=>relatedScore(e,f.q+' '+f.a)>=.25),qr=fullQuestions(c).filter(q=>relatedScore(e,(q.q||'')+' '+(q.why||''))>=.25);
  let fst=fr.map(f=>state.flash[c.id+'-'+f.id]).filter(Boolean),attempts=qr.map(q=>state.qAttempts[c.id+'-'+qid(q)]).filter(Boolean);
  let fscore=fst.length?fst.reduce((sum,x)=>sum+flashStrength(x),0)/fst.length/100:0;
  let qtot=attempts.reduce((sum,a)=>sum+(a.total||0),0),qcorr=attempts.reduce((sum,a)=>sum+(a.correct||0),0),qscore=qtot?qcorr/qtot:0;
  let frep=fst.length?fst.reduce((sum,x)=>sum+Math.min(1,(x.reps||0)/3),0)/fst.length:0;
  let qstable=attempts.length?attempts.reduce((sum,a)=>sum+Math.min(1,(a.streak||0)/2),0)/attempts.length:0;
  let stability=fst.length&&attempts.length?frep*.55+qstable*.45:fst.length?frep:attempts.length?qstable:0;
  let evidence=Math.min(1,(fst.length+qtot)/Math.max(3,Math.min(8,fr.length+qr.length)||3));
  let p=Math.round(checked*10+fscore*30+qscore*40+stability*20);
  if(!fst.length&&!attempts.length)p=checked?10:0;
  if(evidence<.35&&p>70)p=70;
  return {p,checked,fcount:fr.length,qcount:qr.length,attempts:attempts.length,course:checked?100:0,flash:Math.round(fscore*100),qcm:Math.round(qscore*100),stability:Math.round(stability*100),evidence:Math.round(evidence*100)};
}
function masteryStatus(p){return p>=80?['Maîtrisée','mastered']:p>=55?['À consolider','fragile']:p>=15?['En apprentissage','learning']:['Non étudiée','new'];}
function chNotionAvg(c){if(!c.essentials.length)return 0;return Math.round(c.essentials.reduce((s,_,i)=>s+notionMastery(c,i).p,0)/c.essentials.length);}
function chStats(c){let ec=c.essentials.length,done=c.essentials.filter((_,i)=>state.checks[c.id+'-'+i]).length,fs=c.flashcards.length,fdone=c.flashcards.filter(f=>flashStrength(state.flash[c.id+'-'+f.id])>=60).length,q=state.quiz[c.id]||{correct:0,total:0},qscore=q.total?Math.min(1,q.correct/q.total):0,legacy=(ec?done/ec:0)*.35+(fs?fdone/fs:0)*.25+qscore*.4,notions=chNotionAvg(c)/100,p=Math.round(Math.max(legacy*.85,notions)*100);return {p,done,ec,fdone,fs,q,notions:Math.round(notions*100)};}
function overall(){let a=D.map(chStats);return Math.round(a.reduce((s,x)=>s+x.p,0)/a.length);}
function totalQuiz(){let corr=0,total=0;Object.values(state.qAttempts||{}).forEach(q=>{corr+=q.correct||0;total+=q.total||0});if(!total)Object.values(state.quiz||{}).forEach(q=>{corr+=q.correct||0;total+=q.total||0});return {corr,total,p:total?Math.round(corr/total*100):0};}
function errorsCount(){return Object.values(state.errors||{}).reduce((n,a)=>n+(Array.isArray(a)?a.length:0),0);}
function bestExam(){return state.examHistory.length?Math.max(...state.examHistory.map(x=>x.p||0)):null;}
function recordQuestion(cid,id,ok){let k=cid+'-'+id,a=state.qAttempts[k]||{correct:0,total:0,streak:0};a.total++;a.last=Date.now();if(ok){a.correct++;a.streak=(a.streak||0)+1;}else a.streak=0;state.qAttempts[k]=a;}
function addError(cid,q,source='base'){state.errors[cid]=state.errors[cid]||[];let id=qid(q),ex=state.errors[cid].find(e=>String(e.id)===id&&e.source===source);let obj={id,source,q:q.q,answer:q.answer,answerText:answerText(q,q.answer),why:q.why,ts:Date.now(),count:(ex?.count||0)+1};if(ex)Object.assign(ex,obj);else state.errors[cid].push(obj);}
function resolveError(cid,id,source='base'){if(!state.errors[cid])return;state.errors[cid]=state.errors[cid].filter(e=>!(String(e.id)===String(id)&&e.source===source));}

function defaultTarget(){return state.settings.targetDate||'2026-12-15';}
const WEEK_THEMES=[{chapters:[1],label:'Biochimie du vivant'},{chapters:[2,3],label:'Organisation + fonctionnement cellulaire'},{chapters:[4],label:'Génétique'},{chapters:[5],label:'Histologie'},{chapters:[6],label:'Physiologie animale'},{chapters:[7],label:'Microorganismes'},{chapters:[8],label:'Immunologie'},{chapters:[9,10],label:'Évolution + biodiversité'}];
function sessionFor(date,week){let dow=(date.getDay()+6)%7,theme=WEEK_THEMES[week],phase=week<8?'learning':week===8?'consolidation':'exam',chs=theme?.chapters||[];if(phase==='learning'){
  let a=chs[0],b=chs[1]||a,rows=[
    {title:`${chapter(a).title} — apprendre`,duration:40,activities:[{kind:'course',cid:a,label:'Cours ciblé',min:25},{kind:'ess',cid:a,label:'À savoir absolument',min:15}]},
    {title:`${chapter(a).title} — mémoriser`,duration:30,activities:[{kind:'flash',cid:a,label:'Flashcards dues / nouvelles',min:15},{kind:'adaptive',cid:a,label:'10 QCM adaptatifs',min:15}]},
    {title:`${chapter(b).title} — approfondir`,duration:45,activities:[{kind:'course',cid:b,label:'Deuxième partie du cours',min:30},{kind:'ess',cid:b,label:'Rappel actif',min:15}]},
    {title:`Rappel actif + QCM`,duration:25,activities:[{kind:'adaptive',cids:chs,label:'QCM ciblé sur la semaine',min:15},{kind:'errors',cids:chs,label:'Revoir les erreurs',min:10}]},
    {title:'Repos / rattrapage',duration:0,activities:[]},
    {title:`Consolidation — ${theme.label}`,duration:90,activities:[{kind:'flash',cids:chs,label:'Flashcards',min:25},{kind:'adaptive',cids:chs,label:'QCM adaptatif',min:35},{kind:'course',cid:a,label:'Revoir les points faibles',min:30}]},
    {title:'Test cumulatif',duration:60,activities:[{kind:'adaptive',cids:[...new Set(WEEK_THEMES.slice(0,week+1).flatMap(x=>x.chapters))],label:'QCM cumulatif',min:35},{kind:'errors',label:'Correction + carnet d’erreurs',min:25}]}
  ];return {...rows[dow],phase,chapters:chs};
 }
 if(phase==='consolidation'){
   const rows=[
    {title:'Consolidation des notions fragiles',duration:40,activities:[{kind:'adaptive',label:'QCM adaptatif — points faibles',min:25},{kind:'course',label:'Revoir les notions les plus faibles',min:15}]},
    {title:'Flashcards + espagnol',duration:30,activities:[{kind:'flash',label:'Cartes dues',min:15},{kind:'spanish',label:'QCM en espagnol',min:15}]},
    {title:'Entraînement transversal',duration:45,activities:[{kind:'adaptive',label:'20 QCM adaptatifs',min:45}]},
    {title:'Carnet d’erreurs',duration:25,activities:[{kind:'errors',label:'Retester les erreurs',min:25}]},
    {title:'Repos / rattrapage',duration:0,activities:[]},
    {title:'Concours blanc + correction',duration:75,activities:[{kind:'exam',label:'Simulation 30 min',min:30},{kind:'errors',label:'Correction ciblée',min:45}]},
    {title:'Révision cumulative',duration:60,activities:[{kind:'flash',label:'Flashcards dues',min:20},{kind:'adaptive',label:'QCM sur les chapitres fragiles',min:40}]}
   ];return {...rows[dow],phase,chapters:[]};
 }
 const rows=[
  {title:'Flashcards dues + notions faibles',duration:30,activities:[{kind:'flash',label:'Flashcards dues',min:20},{kind:'essweak',label:'5 notions faibles',min:10}]},
  {title:'QCM en espagnol',duration:30,activities:[{kind:'spanish',label:'20 questions espagnoles',min:30}]},
  {title:'Concours blanc 30 min',duration:30,activities:[{kind:'exam',label:'Simulation UAX',min:30}]},
  {title:'Correction ciblée',duration:25,activities:[{kind:'errors',label:'Retester les erreurs récentes',min:25}]},
  {title:'Repos / rattrapage',duration:0,activities:[]},
  {title:'Concours blanc + points faibles',duration:75,activities:[{kind:'exam',label:'Simulation UAX',min:30},{kind:'adaptive',label:'QCM ciblé',min:25},{kind:'flash',label:'Flashcards dues',min:20}]},
  {title:'Révision légère',duration:45,activities:[{kind:'flash',label:'Cartes difficiles uniquement',min:20},{kind:'essweak',label:'Notions fragiles',min:25}]}
 ];return {...rows[dow],phase,chapters:[]};
}
function compactRecovery(base){
  if(!base.duration)return base;
  let cap=Math.min(30,base.duration),left=cap,acts=[];
  for(const a of base.activities||[]){if(left<=0)break;let take=Math.min(left,Math.max(5,Math.min(a.min||10,20)));acts.push({...a,min:take,label:a.label});left-=take;}
  if(!acts.length)acts=[{kind:'adaptive',label:'QCM adaptatif ciblé',min:cap}];
  else if(left>0)acts[acts.length-1].min+=left;
  return {...base,title:`Rattrapage ciblé — ${base.title}`,duration:cap,activities:acts,recovery:true};
}
function planItems(){let start=dateFromIso('2026-10-05'),target=dateFromIso(defaultTarget()),out=[];if(target<start)return out;for(let d=new Date(start);d<=target;d=addDays(d,1)){let week=Math.floor((d-start)/(7*86400000)),base=sessionFor(d,week),id=isoDate(d),st=state.plan[id]||{},actual=st.date||id,item=st.recovery?compactRecovery(base):base;out.push({id,baseDate:id,date:actual,status:st.status||'todo',recovery:!!st.recovery,...item});}return out.sort((a,b)=>a.date.localeCompare(b.date)||a.baseDate.localeCompare(b.baseDate));}
function planForDate(iso){return planItems().filter(x=>x.date===iso);}
function nextPlan(){let t=todayIso();return planItems().find(x=>x.date>=t&&x.status==='todo'&&x.duration>0);}
function planProgress(){let a=planItems().filter(x=>x.duration>0),done=a.filter(x=>x.status==='done').length;return {done,total:a.length,p:a.length?Math.round(done/a.length*100):0};}
function markPlan(id,status){state.plan[id]=Object.assign({},state.plan[id],{status});logActivity('plan',{id,status});}
function occupiedPlanDates(excludeId=null){let set=new Set();for(const x of planItems()){if(x.id===excludeId||x.status==='skip'||!x.duration)continue;if(x.status==='todo'||x.status==='done')set.add(x.date);}return set;}
function findFreePlanDate(fromIso,excludeId=null){let occupied=occupiedPlanDates(excludeId),target=defaultTarget();for(let d=dateFromIso(fromIso);isoDate(d)<=target;d=addDays(d,1)){let iso=isoDate(d);if(!occupied.has(iso))return iso;}return null;}
function overduePlanItems(){let t=todayIso();return planItems().filter(x=>x.status==='todo'&&x.duration>0&&x.date<t);}
function reflowOverdue(){let late=overduePlanItems();if(!late.length)return {moved:0,remaining:0};let occupied=occupiedPlanDates(),moved=0;for(const item of late){occupied.delete(item.date);let slot=null;for(let d=dateFromIso(todayIso());isoDate(d)<=defaultTarget();d=addDays(d,1)){let iso=isoDate(d);if(!occupied.has(iso)){slot=iso;break;}}if(!slot)continue;state.plan[item.id]=Object.assign({},state.plan[item.id],{date:slot,status:'todo',recovery:true});occupied.add(slot);moved++;}save();return {moved,remaining:late.length-moved};}
function deferPlan(id,days=1){let item=planItems().find(x=>x.id===id),base=item?.date||id,desired=isoDate(addDays(dateFromIso(base),days)),slot=findFreePlanDate(desired,id)||desired;state.plan[id]=Object.assign({},state.plan[id],{date:slot,status:'todo',recovery:false});save();}
function weakestNotions(limit=8){let all=[];for(const c of D)c.essentials.forEach((e,i)=>all.push({cid:c.id,i,text:e,...notionMastery(c,i)}));return all.sort((a,b)=>a.p-b.p).slice(0,limit);}
function dailyCard(){let today=planForDate(todayIso()).find(x=>x.status==='todo'&&x.duration>0),next=today||nextPlan(),due=dueFlashRefs(30).filter(r=>state.flash[r.cid+'-'+r.fid]?.due<=Date.now()).length;if(!next)return `<section class="today-card"><div><span class="kicker">Planning</span><h2>Programme terminé</h2><p>Utilise les concours blancs et le carnet d’erreurs pour l’entretien final.</p></div><button class="btn" data-go="planning">Voir le planning</button></section>`;let isToday=next.date===todayIso();return `<section class="today-card today-primary"><div class="today-main"><span class="kicker">${isToday?'Aujourd’hui':'Prochaine séance · '+fmtDate(dateFromIso(next.date),true)}</span><h2>${esc(next.title)}</h2><p>${next.duration?`${next.duration} min · `:''}${due} flashcard(s) arrivée(s) à échéance.${next.recovery?' · séance de rattrapage allégée':''}</p><div class="today-steps">${next.activities.map(a=>`<span>${esc(a.label)} · ${a.min} min</span>`).join('')}</div></div><div class="today-actions"><button class="btn primary big" data-plan-open="${next.id}">Commencer ma séance</button><button class="btn" data-go="planning">Planning complet</button></div></section>`;}
function renderNav(){return `<div class="brand"><b>UAX Biologie</b><span>Préparation concours · Madrid</span></div>
<button class="nav-btn ${view.type==='dashboard'?'active':''}" data-go="dashboard"><span class="nav-num">⌂</span>Tableau de bord</button>
<button class="nav-btn ${view.type==='today'?'active':''}" data-go="today"><span class="nav-num">▶</span>Ma séance</button>
<button class="nav-btn ${view.type==='planning'?'active':''}" data-go="planning"><span class="nav-num">▦</span>Planning</button>
<button class="nav-btn ${view.type==='review'?'active':''}" data-go="review"><span class="nav-num">↻</span>Révisions flashcards</button>
<button class="nav-btn ${view.type==='practice'?'active':''}" data-go="practice"><span class="nav-num">◎</span>QCM adaptatif</button>
<button class="nav-btn exam-nav ${view.type==='exam'?'active':''}" data-go="exam"><span class="nav-num">⏱</span>Mode concours 30 min</button>
<div class="nav-section">Chapitres</div>${D.map(c=>`<button class="nav-btn ${view.type==='chapter'&&view.chapter===c.id?'active':''}" data-ch="${c.id}"><span class="nav-num">${c.id}</span>${esc(c.title)}</button>`).join('')}
<div class="nav-section">Outils</div><button class="nav-btn ${view.type==='search'?'active':''}" data-go="search"><span class="nav-num">⌕</span>Recherche</button><button class="nav-btn ${view.type==='errors'?'active':''}" data-go="errors"><span class="nav-num">!</span>Carnet d’erreurs</button><button class="nav-btn ${view.type==='stats'?'active':''}" data-go="stats"><span class="nav-num">↗</span>Statistiques</button>`;}
function topbar(title='Préparation UAX'){return `<div class="topbar"><div style="display:flex;gap:10px;align-items:center"><button class="btn mobile-menu" id="menu" aria-label="Ouvrir le menu">☰</button><h1>${esc(title)}</h1></div><div class="top-actions"><label class="lang-control"><span>Langue</span><select id="langSelect" aria-label="Langue d'entraînement"><option value="fr" ${state.settings.lang==='fr'?'selected':''}>FR</option><option value="mix" ${state.settings.lang==='mix'?'selected':''}>FR/ES</option><option value="es" ${state.settings.lang==='es'?'selected':''}>ES QCM</option></select></label><button class="btn hide-sm" id="export">Exporter</button><button class="btn hide-sm" id="import">Importer</button><button class="btn" id="theme" aria-label="Mode clair ou sombre">◐</button></div></div>`;}
function dashboard(){let ov=overall(),t=totalQuiz(),due=dueFlashRefs(30).filter(r=>state.flash[r.cid+'-'+r.fid]?.due<=Date.now()).length,late=overduePlanItems(),weak=weakestNotions(5),goal=weak[0],pp=planProgress();return `${topbar('Préparation UAX — Biologie')}<div class="dashboard-focus">${dailyCard()}<aside class="progress-focus"><span class="kicker">Maîtrise globale</span><div class="focus-score">${ov}%</div><div class="focus-progress"><i style="width:${ov}%"></i></div><p>${goal?`Prochain objectif : renforcer <b>${esc(goal.text)}</b> (chapitre ${goal.cid}).`:'Continue le planning et les concours blancs.'}</p><div class="focus-actions"><button class="btn" id="startAdaptive">QCM adaptatif</button><button class="btn" data-go="exam">Concours 30 min</button></div></aside></div>${late.length?`<section class="recovery-alert"><div><b>${late.length} séance(s) en retard</b><span>Le site peut les transformer en rattrapages ciblés de 30 min maximum et les placer sur les prochains créneaux libres.</span></div><button class="btn primary" id="reflowPlan">Réorganiser sans surcharge</button></section>`:''}<div class="stat-grid compact-stats"><div class="stat"><b>${due}</b><span>flashcards dues</span></div><div class="stat"><b>${errorsCount()}</b><span>erreurs actives</span></div><div class="stat"><b>${t.total?t.p+'%':'—'}</b><span>réussite QCM</span></div><div class="stat"><b>${pp.p}%</b><span>planning réalisé</span></div></div><section class="priority-panel"><div class="section-title"><h2>Mes 5 priorités</h2><span>calculées à partir des flashcards et QCM</span></div><div class="priority-grid">${weak.map((x,n)=>`<button class="priority-item" data-weak-open="${x.cid}|${x.i}"><span>${n+1}</span><div><b>${esc(x.text)}</b><small>Chapitre ${x.cid} · maîtrise ${x.p}% · stabilité ${x.stability}%</small></div></button>`).join('')}</div></section><div class="section-title"><h2>Les 10 chapitres</h2><span>ouvrir un chapitre pour apprendre ou réviser</span></div><div class="chapter-grid">${D.map(c=>{let s=chStats(c),w=weakNotionsForChapter(c,1)[0];return `<article class="chapter-card" data-ch="${c.id}" tabindex="0" role="button"><div class="chapter-head"><div class="chapter-index">${c.id}</div><div><h3>${esc(c.title)}</h3><p>${esc(c.description)}</p></div></div><div class="mini-progress"><i style="width:${s.p}%"></i></div><div class="card-foot"><span>maîtrise notionnelle ${s.notions}%</span><span>${s.p}%</span></div>${w?`<div class="weak-line">À renforcer : ${esc(w.text)}</div>`:''}</article>`}).join('')}</div>`;}
function weakNotionsForChapter(c,limit=3){return c.essentials.map((e,i)=>({text:e,i,...notionMastery(c,i)})).sort((a,b)=>a.p-b.p).slice(0,limit);}

function chapterView(){let c=chapter(view.chapter),s=chStats(c);state.lastChapter=c.id;save();let course=`<div class="course">${view.highlight?`<div class="focus-banner">Ouvert depuis une erreur/recherche : <b>${esc(view.highlight)}</b></div>`:''}${c.courseHtml}${state.settings.lang!=='fr'?vocabHtml(stripHtml(c.courseHtml),12):''}</div>`;return `${topbar(c.title)}<div class="chapter-page"><section class="chapter-banner"><div class="kicker">Chapitre ${c.id} · UAX</div><h2>${esc(c.title)}</h2><p>${esc(c.description)} · Progression ${s.p}% · Maîtrise notionnelle ${s.notions}%</p></section><div class="tabs">${[['course','Cours'],['ess','À savoir'],['flash','Flashcards'],['quiz','QCM']].map(([k,l])=>`<button class="tab ${view.tab===k?'active':''}" data-tab="${k}" aria-pressed="${view.tab===k}">${l}</button>`).join('')}</div><section class="content-panel">${view.tab==='course'?course:view.tab==='ess'?essView(c):view.tab==='flash'?flashView(c):quizView(c)}</section></div>`;}
function essView(c){return `<div class="toolbar"><div><b>Maîtrise par notion</b><div class="pill">Cours 10 % · flashcards 30 % · QCM 40 % · stabilité dans le temps 20 %.</div></div><button class="btn" id="uncheck">Tout décocher</button></div><div class="mastery-list">${c.essentials.map((x,i)=>{let k=c.id+'-'+i,v=!!state.checks[k],m=notionMastery(c,i),[label,cls]=masteryStatus(m.p);return `<div class="mastery-row ${cls}"><label class="check compact ${v?'done':''}"><input type="checkbox" data-check="${k}" ${v?'checked':''}><span>${esc(x)}</span></label><div><div class="mastery-meta"><span class="mastery-status">${label}</span><div class="mastery-bar"><i style="width:${m.p}%"></i></div><b>${m.p}%</b></div><div class="mastery-breakdown"><span>Cours ${m.course}%</span><span>Flash ${m.flash}%</span><span>QCM ${m.qcm}%</span><span>Stabilité ${m.stability}%</span></div></div></div>`}).join('')}</div>`;}
function flashPool(c){return c.flashcards;}
function pickFlash(c){let p=flashPool(c);if(view.fcIndex>=p.length)view.fcIndex=0;return p[view.fcIndex];}
function dueText(st){if(!st)return 'nouvelle';let d=st.due-Date.now();if(d<=0)return 'à revoir maintenant';if(d<86400000)return `dans ${Math.max(1,Math.round(d/3600000))} h`;return `dans ${Math.max(1,Math.round(d/86400000))} j`;}
function flashView(c){let f=pickFlash(c),st=state.flash[c.id+'-'+f.id]||null,text=view.fcFlip?f.a:f.q;return `<div class="toolbar"><span class="pill">Carte ${view.fcIndex+1}/${c.flashcards.length}</span><span class="pill">${dueText(st)} · force ${flashStrength(st)}%</span></div><div class="flash-wrap"><div class="flash-card" id="flip" role="button" tabindex="0" aria-label="Retourner la flashcard"><div><div class="flash-label">${view.fcFlip?'Réponse':'Question'} · clic ou espace</div><div class="flash-text">${esc(text)}</div>${vocabHtml(text,5)}</div></div>${view.fcFlip?`<div class="flash-controls"><button class="btn diff hard" data-rating="0">Oublié</button><button class="btn diff hard" data-rating="1">Difficile</button><button class="btn diff mid" data-rating="2">Correct</button><button class="btn diff easy" data-rating="3">Facile</button></div>`:'<div class="flash-controls"><button class="btn primary" id="showAnswer">Afficher la réponse</button></div>'}<div class="flash-controls"><button class="btn" id="prevFc">← Précédente</button><button class="btn" id="nextFc">Suivante →</button></div></div>`;}
function quizView(c){let p=poolForChapter(c);if(view.qIndex>=p.length)view.qIndex=0;let q=p[view.qIndex],order=seededOrder(q,`${c.id}-${qid(q)}-${todayIso()}`),d=difficulty(c,q);return `<div class="quiz-box"><div class="toolbar"><div class="quiz-filters"><button class="pill-btn ${view.qDifficulty==='all'?'active':''}" data-diff="all">Tous</button>${[1,2,3].map(n=>`<button class="pill-btn ${String(view.qDifficulty)===String(n)?'active':''}" data-diff="${n}">${DIFF_LABEL[n]}</button>`).join('')}<button class="pill-btn adaptive" id="chapterAdaptive">Adaptatif · 10</button></div><span class="pill">${state.settings.lang==='es'?'Questions ES disponibles':'Réponses mélangées'}</span></div><div class="quiz-meta"><span>Question ${view.qIndex+1}/${p.length}</span><span>${DIFF_LABEL[d]} · ${esc(c.title)}</span></div>${q.svg?`<div class="visual-q">${q.svg}</div>`:''}<div class="quiz-q">${esc(questionText(q))}</div>${vocabHtml(questionText(q),4)}<div class="answers">${displayOptions(q,order,'data-answer')}</div><div id="feedback" aria-live="polite"></div><div class="flash-controls" style="justify-content:flex-end"><button class="btn" id="nextQ" disabled>Question suivante →</button></div></div>`;}

function reviewView(){if(!view.reviewRefs.length)view.reviewRefs=dueFlashRefs(30);if(!view.reviewRefs.length)return `${topbar('Révisions flashcards')}<div class="chapter-page"><section class="content-panel"><div class="empty"><h2>Aucune carte due</h2><p>Les cartes déjà vues reviendront automatiquement au bon moment. Tu peux lancer un QCM adaptatif.</p><button class="btn primary" id="startAdaptive">QCM adaptatif</button></div></section></div>`;if(view.reviewIndex>=view.reviewRefs.length)view.reviewIndex=0;let ref=view.reviewRefs[view.reviewIndex],c=chapter(ref.cid),f=c.flashcards.find(x=>String(x.id)===String(ref.fid)),st=state.flash[c.id+'-'+f.id],text=view.reviewFlip?f.a:f.q;return `${topbar('Révisions du jour')}<div class="chapter-page"><section class="chapter-banner"><div class="kicker">Répétition espacée</div><h2>${view.reviewRefs.length} cartes dans cette séance</h2><p>Évalue la difficulté après avoir révélé la réponse. Le prochain intervalle est calculé automatiquement.</p></section><section class="content-panel" style="margin-top:18px"><div class="toolbar"><span class="pill">${view.reviewIndex+1}/${view.reviewRefs.length} · Chapitre ${c.id}</span><span class="pill">${dueText(st)}</span></div><div class="flash-wrap"><div class="flash-card" id="reviewFlip" tabindex="0"><div><div class="flash-label">${view.reviewFlip?'Réponse':'Question'}</div><div class="flash-text">${esc(text)}</div>${vocabHtml(text,5)}</div></div>${view.reviewFlip?`<div class="flash-controls"><button class="btn diff hard" data-review-rating="0">Oublié</button><button class="btn diff hard" data-review-rating="1">Difficile</button><button class="btn diff mid" data-review-rating="2">Correct</button><button class="btn diff easy" data-review-rating="3">Facile</button></div>`:'<div class="flash-controls"><button class="btn primary" id="reviewFlipBtn">Afficher la réponse</button></div>'}</div></section></div>`;}

function adaptiveRefs(count=10,scope=null){let cids=scope?.length?scope.map(Number):D.map(c=>c.id),errs=[];for(const cid of cids)(state.errors[cid]||[]).forEach(e=>errs.push({cid,source:e.source||'base',qid:String(e.id),score:220}));let candidates=[];for(const cid of cids){let c=chapter(cid),weak=100-chStats(c).p;for(const q of fullQuestions(c)){if(state.settings.lang==='es'&&!(q.qEs||looksSpanish(q.q)))continue;let a=state.qAttempts[cid+'-'+qid(q)],acc=a?.total?a.correct/a.total:.5,score=weak+(1-acc)*70+(a?.streak===0&&a?.total?30:0)+Math.random()*30;candidates.push({...makeRef(cid,q),score});}}let used=new Set(),out=[];for(const x of [...errs,...candidates.sort((a,b)=>b.score-a.score)]){let k=x.cid+'-'+x.source+'-'+x.qid;if(!used.has(k)){used.add(k);out.push({cid:x.cid,source:x.source,qid:x.qid});if(out.length>=count)break;}}return shuffle(out);}
function startPractice(count=10,scope=null,refs=null){let list=refs||adaptiveRefs(count,scope);state.practiceLast=null;state.practiceActive={refs:list,index:0,answers:{},orders:{},correct:0,startedAt:Date.now(),scope:scope||null};save();view.type='practice';render();}
function practiceView(){let p=state.practiceActive;if(!p)return practiceStartView();if(p.index>=p.refs.length)return finishPractice();let ref=p.refs[p.index],{c,q}=getRef(ref);if(!q){p.index++;save();return practiceView();}let order=p.orders[p.index]||(p.orders[p.index]=seededOrder(q,`practice-${p.startedAt}-${p.index}`)),ans=p.answers[p.index],done=!!ans,ok=done&&ans===q.answer;save();return `${topbar('QCM adaptatif')}<div class="chapter-page"><section class="content-panel"><div class="quiz-box"><div class="quiz-meta"><span>Question ${p.index+1}/${p.refs.length}</span><span>Chapitre ${c.id} · ${DIFF_LABEL[difficulty(c,q)]}</span></div>${q.svg?`<div class="visual-q">${q.svg}</div>`:''}<div class="quiz-q">${esc(questionText(q))}</div>${vocabHtml(questionText(q),4)}<div class="answers">${displayOptions(q,order,'data-practice-answer',ans,done)}</div>${done?`<div class="feedback ${ok?'good':'bad'}"><b>${ok?'Bonne réponse.':'À revoir.'}</b> ${esc(questionWhy(q))}${!ok?`<div class="feedback-actions"><button class="btn" data-error-course="${c.id}" data-error-term="${esc(tokens(q.q)[0]||q.q.slice(0,30))}">Revoir dans le cours</button></div>`:''}</div>`:'<div id="feedback" aria-live="polite"></div>'}<div class="flash-controls" style="justify-content:flex-end">${done?`<button class="btn primary" id="practiceNext">${p.index===p.refs.length-1?'Voir le bilan':'Question suivante →'}</button>`:''}</div></div></section></div>`;}
function practiceStartView(){return `${topbar('QCM adaptatif')}<div class="chapter-page"><section class="chapter-banner"><div class="kicker">Entraînement personnalisé</div><h2>Le site choisit les questions à ta place.</h2><p>Priorité aux chapitres faibles, aux erreurs récentes et aux questions peu réussies. Les propositions A/B/C/D sont mélangées.</p></section><section class="content-panel" style="margin-top:18px"><div class="practice-counts">${[10,20,30].map(n=>`<button class="count-card light" data-practice-count="${n}"><strong>${n}</strong><span>questions</span></button>`).join('')}</div></section></div>`;}
function finishPractice(){let p=state.practiceActive;if(!p)return;let total=p.refs.length,correct=Object.entries(p.answers).filter(([i,a])=>{let {q}=getRef(p.refs[+i]);return q&&a===q.answer}).length;state.practiceLast={date:Date.now(),total,correct,p:total?Math.round(correct/total*100):0};state.practiceActive=null;logActivity('practice',{correct,total});render();}
function practiceResultView(){let r=state.practiceLast;return `${topbar('Bilan QCM adaptatif')}<div class="chapter-page"><section class="result-hero"><div><div class="kicker">Séance terminée</div><h2>${r.p}%</h2><p>${r.correct}/${r.total} bonnes réponses. Les erreurs ont été ajoutées au carnet.</p></div><div class="result-gauge"><span>${r.p}%</span><small>${r.p>=80?'solide sur cette séance':'reprends les erreurs avant une nouvelle série'}</small></div></section><div class="exam-result-actions"><button class="btn" data-go="errors">Revoir les erreurs</button><button class="btn primary" id="againAdaptive">Nouvelle série</button></div></div>`;}

function errorCards(){let cards=[];D.forEach(c=>(state.errors[c.id]||[]).forEach(e=>cards.push({c,e})));return cards.sort((a,b)=>(b.e.ts||0)-(a.e.ts||0));}
function errorsView(){let cards=errorCards();return `${topbar('Carnet d’erreurs')}<div class="chapter-page"><section class="chapter-banner"><div class="kicker">Boucle de correction</div><h2>Erreur → explication → cours → retest</h2><p>Une erreur disparaît du carnet après un retest réussi.</p></section><section class="content-panel" style="margin-top:18px">${cards.length?`<div class="toolbar"><span class="pill">${cards.length} erreur(s) active(s)</span><button class="btn danger" id="clearErrors">Effacer le carnet</button></div><div class="errors">${cards.map(({c,e})=>`<div class="error-card"><b>Chapitre ${c.id} — ${esc(c.title)}</b><div>${esc(e.q)}</div><small>Bonne réponse : ${esc(e.answerText||e.answer)}<br>${esc(e.why)}</small><div class="error-actions"><button class="btn" data-error-course="${c.id}" data-error-term="${esc(tokens(e.q)[0]||e.q.slice(0,30))}">Revoir dans le cours</button><button class="btn primary" data-error-retest="${c.id}|${esc(e.source||'base')}|${esc(e.id)}">Retester maintenant</button></div></div>`).join('')}</div>`:'<div class="empty">Aucune erreur active. Les prochains QCM alimenteront automatiquement ce carnet.</div>'}</section></div>`;}

function searchData(q){let n=norm(q);if(n.length<2)return [];let out=[];for(const c of D){let course=stripHtml(c.courseHtml),pos=norm(course).indexOf(n);if(pos>=0){let raw=course.slice(Math.max(0,pos-90),pos+180);out.push({type:'Cours',cid:c.id,label:c.title,snippet:raw});}c.essentials.forEach((x,i)=>{if(norm(x).includes(n))out.push({type:'Notion',cid:c.id,index:i,label:x,snippet:'À savoir absolument'});});c.flashcards.forEach((f,i)=>{if(norm(f.q+' '+f.a).includes(n))out.push({type:'Flashcard',cid:c.id,index:i,label:f.q,snippet:f.a});});fullQuestions(c).forEach((x,i)=>{if(norm((x.q||'')+' '+(x.why||'')).includes(n))out.push({type:'QCM',cid:c.id,index:i,label:x.q,snippet:x.why||''});});}return out.slice(0,60);}
function searchView(){let r=searchData(view.searchQuery);return `${topbar('Recherche globale')}<div class="chapter-page"><section class="content-panel"><form id="searchForm" class="search-form"><input id="searchInput" value="${esc(view.searchQuery)}" placeholder="Ex. osmose, plasmide, lymphocyte B…" aria-label="Rechercher"><button class="btn primary">Rechercher</button></form>${view.searchQuery?`<p class="muted">${r.length} résultat(s) pour « ${esc(view.searchQuery)} »</p><div class="search-results">${r.map(x=>`<button class="search-result" data-search-open="${x.cid}|${x.type}|${x.index??0}"><span class="result-type">${x.type} · chapitre ${x.cid}</span><b>${esc(x.label)}</b><small>${esc(x.snippet)}</small></button>`).join('')}</div>`:'<div class="empty">Recherche dans les cours, notions essentielles, flashcards et QCM.</div>'}</section></div>`;}

function planningView(){let items=planItems(),today=todayIso(),target=defaultTarget(),late=overduePlanItems(),shown;if(view.planMode==='today')shown=items.filter(x=>x.date===today);else if(view.planMode==='week'){let d=new Date(),monday=addDays(d,-((d.getDay()+6)%7)),end=addDays(monday,6),a=isoDate(monday),b=isoDate(end);shown=items.filter(x=>x.date>=a&&x.date<=b);}else shown=items;let pp=planProgress();return `${topbar('Planning jusqu’au concours')}<div class="chapter-page"><section class="chapter-banner"><div class="kicker">Parcours guidé et flexible</div><h2>${pp.p}% du planning réalisé</h2><p>Lundi 40 min · mardi 30 min · mercredi 45 min · jeudi 25 min · vendredi tampon · samedi 1 h 30 · dimanche 1 h environ. Un retard peut être converti en rattrapage ciblé de 30 min maximum, sans empiler deux grosses séances le même jour.</p><div class="target-date"><label>Date cible du concours <input id="targetDate" type="date" value="${esc(target)}"></label><button class="btn" id="saveTarget">Enregistrer</button><small>Date indicative tant que la date UAX exacte n’est pas renseignée.</small></div></section>${late.length?`<section class="recovery-alert plan-recovery"><div><b>${late.length} séance(s) passée(s) non faite(s)</b><span>Réorganisation proposée : prochains créneaux libres, séances compactées à 30 min maximum.</span></div><button class="btn primary" id="reflowPlan">Réorganiser</button></section>`:''}<div class="tabs plan-tabs"><button class="tab ${view.planMode==='today'?'active':''}" data-plan-mode="today">Aujourd’hui</button><button class="tab ${view.planMode==='week'?'active':''}" data-plan-mode="week">Cette semaine</button><button class="tab ${view.planMode==='all'?'active':''}" data-plan-mode="all">Jusqu’au concours</button></div><section class="content-panel"><div class="plan-list">${shown.length?shown.map(planRow).join(''):`<div class="empty">Aucune séance prévue dans cette vue. ${view.planMode==='today'?'<br>Profite du jour tampon ou lance une courte révision.':''}</div>`}</div></section></div>`;}
function planRow(x){let cls=x.status==='done'?'done':x.status==='skip'?'skipped':'',phase={learning:'Apprentissage',consolidation:'Consolidation',exam:'Mode concours'}[x.phase]||'';return `<article class="plan-row ${cls} ${x.recovery?'recovery':''}"><div class="plan-date"><b>${fmtDate(dateFromIso(x.date),true)}</b><span>${x.recovery?'Rattrapage ciblé':phase}</span></div><div class="plan-body"><h3>${esc(x.title)}</h3><div class="plan-activities">${x.activities.length?x.activities.map(a=>`<button class="activity-chip" data-activity="${esc(a.kind)}" data-cid="${a.cid||''}" data-cids="${esc((a.cids||[]).join(','))}">${esc(a.label)} <small>${a.min} min</small></button>`).join(''):'<span class="muted">Aucune séance obligatoire.</span>'}</div></div><div class="plan-duration">${x.duration?x.duration+' min':'—'}</div><div class="plan-actions">${x.duration&&x.status==='todo'?`<button class="btn small" data-plan-done="${x.id}">Fait</button><button class="btn small" data-plan-defer="${x.id}">Reporter</button><button class="btn small danger" data-plan-skip="${x.id}">Ignorer</button>`:x.status==='done'?'<span class="done-label">✓ Fait</span>':x.status==='skip'?'<span class="muted">Ignoré</span>':''}</div></article>`;}
function todayView(){let late=overduePlanItems(),item=planForDate(todayIso()).find(x=>x.status==='todo'&&x.duration>0)||nextPlan();if(!item)return `${topbar('Ma séance')}<div class="chapter-page"><section class="content-panel"><div class="empty">Le planning prévu est terminé. Lance un concours blanc ou une révision adaptative.</div></section></div>`;let future=item.date!==todayIso();return `${topbar('Ma séance')}<div class="chapter-page">${late.length?`<section class="recovery-alert"><div><b>${late.length} séance(s) à réorganiser</b><span>Le rattrapage peut être allégé et placé sur les prochains créneaux libres.</span></div><button class="btn" id="reflowPlan">Réorganiser</button></section>`:''}<section class="session-hero"><span class="kicker">${future?'Prochaine séance · '+fmtDate(dateFromIso(item.date),true):'Aujourd’hui'}${item.recovery?' · rattrapage ciblé':''}</span><h2>${esc(item.title)}</h2><p>${item.duration} minutes prévues. Tu peux faire les blocs séparément selon ton emploi du temps.</p></section><section class="content-panel" style="margin-top:18px"><div class="session-steps">${item.activities.map((a,i)=>`<div class="session-step"><span class="step-num">${i+1}</span><div><b>${esc(a.label)}</b><small>${a.min} minutes</small></div><button class="btn primary" data-activity="${esc(a.kind)}" data-cid="${a.cid||''}" data-cids="${esc((a.cids||[]).join(','))}">Commencer</button></div>`).join('')}</div><div class="session-footer"><button class="btn" data-plan-defer="${item.id}">Reporter au prochain créneau libre</button><button class="btn primary" data-plan-done="${item.id}">Marquer la séance faite</button></div></section></div>`;}
function statsView(){let pp=planProgress(),t=totalQuiz(),weak=weakestNotions(10),hist=state.examHistory.slice(0,8).reverse(),days={};for(const a of state.activity){let d=isoDate(new Date(a.t));days[d]=(days[d]||0)+1;}let recent=[...Array(14)].map((_,i)=>{let d=isoDate(addDays(new Date(),i-13));return {d,n:days[d]||0};});return `${topbar('Statistiques')}<div class="chapter-page"><div class="stat-grid"><div class="stat"><b>${overall()}%</b><span>progression globale</span></div><div class="stat"><b>${t.total?t.p+'%':'—'}</b><span>réussite aux questions</span></div><div class="stat"><b>${pp.p}%</b><span>planning réalisé</span></div><div class="stat"><b>${errorsCount()}</b><span>erreurs actives</span></div></div><section class="content-panel"><div class="section-title"><h2>Maîtrise par chapitre</h2><span>basée sur notions, flashcards et QCM</span></div><div class="chapter-results">${D.map(c=>{let p=chStats(c).notions;return `<div class="result-row"><div><b>${c.id}. ${esc(c.title)}</b><span>${p}%</span></div><div class="result-bar"><i style="width:${p}%"></i></div><strong>${p}%</strong></div>`}).join('')}</div></section><section class="content-panel result-panel"><div class="section-title"><h2>Notions les plus fragiles</h2><span>priorités automatiques</span></div><div class="weak-grid">${weak.map(x=>`<button class="weak-card" data-weak-open="${x.cid}|${x.i}"><b>${x.p}%</b><span>Ch. ${x.cid} · ${esc(x.text)}</span></button>`).join('')}</div></section><section class="content-panel result-panel"><div class="section-title"><h2>Activité — 14 derniers jours</h2></div><div class="activity-strip">${recent.map(x=>`<div class="day-block level-${Math.min(4,x.n)}" title="${x.d} : ${x.n} activité(s)"><span>${x.n||''}</span></div>`).join('')}</div></section><section class="content-panel result-panel"><div class="section-title"><h2>Concours blancs</h2></div>${hist.length?`<div class="exam-trend">${hist.map(x=>`<div class="trend-col"><span style="height:${Math.max(4,x.p)}%"></span><b>${x.p}%</b></div>`).join('')}</div>`:'<div class="empty">Aucune simulation terminée pour le moment.</div>'}</section></div>`;}

function balancedRefs(count){let order=shuffle(D.map(c=>c.id)),base=Math.floor(count/D.length),rem=count%D.length,refs=[];order.forEach((cid,idx)=>{let c=chapter(cid),pool=fullQuestions(c);if(state.settings.lang==='es')pool=pool.filter(q=>q.qEs||looksSpanish(q.q));let n=base+(idx<rem?1:0);shuffle(pool).slice(0,n).forEach(q=>refs.push(makeRef(cid,q)));});return shuffle(refs);}
function examStartView(){let hist=state.examHistory.slice(0,5);return `${topbar('Mode concours UAX')}<div class="exam-page"><section class="exam-intro"><div class="kicker">Simulation chronométrée</div><h2>30 minutes. 10 chapitres. Correction à la fin.</h2><p>Les questions et les propositions A/B/C/D sont mélangées. En mode ES, le moteur utilise en priorité les questions espagnoles disponibles. Le nombre exact de questions de l’UAX n’étant pas publié dans nos sources, choisis un volume d’entraînement.</p><div class="exam-counts">${[20,30,40].map(n=>`<button class="count-card ${view.examCount===n?'active':''}" data-exam-count="${n}"><strong>${n}</strong><span>questions</span></button>`).join('')}</div><button class="btn primary exam-start" id="startExam">Démarrer ${view.examCount} questions</button><p class="exam-note">Une simulation interrompue reste enregistrée et peut être reprise.</p></section>${state.examActive?'<button class="btn primary" id="resumeExam">Reprendre la simulation en cours</button>':''}${hist.length?`<section class="history-panel"><div class="section-title"><h2>Dernières simulations</h2><span>meilleur score ${bestExam()}%</span></div><div class="history-list">${hist.map(h=>`<div class="history-row"><span>${new Date(h.date).toLocaleString('fr-FR',{dateStyle:'medium',timeStyle:'short'})}</span><b>${h.p}%</b><span>${h.correct}/${h.total}</span></div>`).join('')}</div></section>`:''}</div>`;}
function activeExamView(){let e=state.examActive,idx=e.current||0,ref=e.questions[idx],{c,q}=getRef(ref);if(!q){e.current++;save();return activeExamView();}let order=e.orders?.[idx]||(e.orders[idx]=seededOrder(q,`exam-${e.startedAt}-${idx}`)),sel=e.answers?.[idx]||null,left=Math.max(0,e.endAt-Date.now());save();return `${topbar('Concours blanc en cours')}<div class="exam-page"><div class="exam-status"><div><span class="pill">Question ${idx+1}/${e.questions.length}</span><span class="pill">Chapitre ${c.id}</span><span class="pill">${DIFF_LABEL[difficulty(c,q)]}</span></div><div class="timer ${left<300000?'urgent':''}" id="examTimer" aria-live="polite">${formatTime(left)}</div></div><div class="exam-layout"><section class="exam-question">${q.svg?`<div class="visual-q">${q.svg}</div>`:''}<div class="quiz-q">${esc(questionText(q))}</div><div class="answers">${displayOptions(q,order,'data-exam-answer',sel,false)}</div><div class="exam-actions"><button class="btn" id="prevExam" ${idx===0?'disabled':''}>← Précédente</button><button class="btn ${e.marked?.[idx]?'marked':''}" id="markExam">${e.marked?.[idx]?'★ À revoir':'☆ Marquer'}</button><button class="btn primary" id="nextExam">${idx===e.questions.length-1?'Récapitulatif':'Suivante →'}</button></div></section><aside class="exam-nav-grid"><h3>Questions</h3><div class="question-grid">${e.questions.map((_,i)=>`<button class="qdot ${i===idx?'current':''} ${e.answers?.[i]?'answered':''} ${e.marked?.[i]?'flagged':''}" data-exam-jump="${i}" aria-label="Question ${i+1}">${i+1}</button>`).join('')}</div><div class="exam-legend"><span><i class="lg answered"></i>répondue</span><span><i class="lg flagged"></i>à revoir</span></div><button class="btn danger full" id="finishExam">Terminer l’épreuve</button></aside></div></div>`;}
function examResultView(){let r=state.examLast;if(!r)return examStartView();return `${topbar('Résultat du concours blanc')}<div class="exam-page"><section class="result-hero"><div><div class="kicker">Simulation terminée</div><h2>${r.p}%</h2><p>${r.correct} bonnes réponses sur ${r.total} · ${r.unanswered} non répondue(s)</p></div><div class="result-gauge"><span>${r.p}%</span><small>${r.p>=85?'maîtrise élevée sur cette simulation':r.p>=70?'base correcte, quelques lacunes persistent':'révisions ciblées recommandées'}</small></div></section><section class="content-panel result-panel"><div class="section-title"><h2>Résultat par chapitre</h2><span>repère les thèmes faibles</span></div><div class="chapter-results">${D.map(c=>{let x=r.byChapter[c.id]||{correct:0,total:0},p=x.total?Math.round(x.correct/x.total*100):0;return `<div class="result-row"><div><b>${c.id}. ${esc(c.title)}</b><span>${x.correct}/${x.total}</span></div><div class="result-bar"><i style="width:${p}%"></i></div><strong>${p}%</strong></div>`}).join('')}</div></section>${r.wrong.length?`<section class="content-panel result-panel"><div class="section-title"><h2>Questions à revoir</h2><span>${r.wrong.length} erreur(s)</span></div><div class="errors">${r.wrong.map(w=>`<div class="error-card"><b>Chapitre ${w.cid} — ${esc(chapter(w.cid).title)}</b><div>${esc(w.q)}</div><small>Ta réponse : ${esc(w.userText||'aucune')} · Bonne réponse : ${esc(w.answerText)}<br>${esc(w.why)}</small><div class="error-actions"><button class="btn" data-error-course="${w.cid}" data-error-term="${esc(tokens(w.q)[0]||'')}">Revoir le cours</button><button class="btn primary" data-error-retest="${w.cid}|${w.source}|${w.id}">Retester</button></div></div>`).join('')}</div></section>`:''}<div class="exam-result-actions"><button class="btn" data-go="dashboard">Tableau de bord</button><button class="btn" data-go="errors">Carnet d’erreurs</button><button class="btn primary" id="newExam">Nouvelle simulation</button></div></div>`;}
function examView(){if(state.examActive&&state.examActive.endAt<=Date.now())submitExam(true,false);if(state.examActive)return activeExamView();if(state.examLast)return examResultView();return examStartView();}
function startExam(count){state.examLast=null;let refs=balancedRefs(count);state.examActive={count,questions:refs,answers:{},marked:{},orders:{},startedAt:Date.now(),endAt:Date.now()+30*60*1000,current:0};logActivity('exam-start',{count});view.type='exam';render();}
function submitExam(timeout=false,doRender=true){let e=state.examActive;if(!e)return;let correct=0,byChapter={},wrong=[];e.questions.forEach((ref,i)=>{let {q}=getRef(ref);if(!q)return;let user=e.answers?.[i]||'',ok=user===q.answer;recordQuestion(ref.cid,qid(q),ok);byChapter[ref.cid]=byChapter[ref.cid]||{correct:0,total:0};byChapter[ref.cid].total++;if(ok){correct++;byChapter[ref.cid].correct++;resolveError(ref.cid,qid(q),ref.source);}else{wrong.push({cid:ref.cid,id:qid(q),source:ref.source,q:questionText(q),userText:user?answerText(q,user):'',answerText:answerText(q,q.answer),why:questionWhy(q)});addError(ref.cid,q,ref.source);}});let total=e.questions.length,result={date:Date.now(),correct,total,p:total?Math.round(correct/total*100):0,unanswered:total-Object.keys(e.answers||{}).length,byChapter,wrong,timeout};state.examHistory.unshift({date:result.date,correct,total,p:result.p});state.examHistory=state.examHistory.slice(0,30);state.examLast=result;state.examActive=null;logActivity('exam',{correct,total,p:result.p});if(doRender){view.type='exam';render();}}

function render(){if(timerHandle){clearInterval(timerHandle);timerHandle=null;}document.body.classList.toggle('dark',!!state.settings.dark);let content=view.type==='dashboard'?dashboard():view.type==='chapter'?chapterView():view.type==='errors'?errorsView():view.type==='exam'?examView():view.type==='planning'?planningView():view.type==='today'?todayView():view.type==='review'?reviewView():view.type==='practice'?(state.practiceLast&&!state.practiceActive?practiceResultView():practiceView()):view.type==='search'?searchView():view.type==='stats'?statsView():dashboard();$('#app').innerHTML=`<a class="skip-link" href="#main">Aller au contenu</a><div class="shell"><aside class="sidebar" id="side">${renderNav()}</aside><main class="main" id="main" tabindex="-1">${content}</main></div>`;bind();if(view.type==='exam'&&state.examActive)startTimer();}
function startTimer(){timerHandle=setInterval(()=>{let e=state.examActive;if(!e){clearInterval(timerHandle);return;}let left=e.endAt-Date.now(),el=$('#examTimer');if(left<=0){clearInterval(timerHandle);submitExam(true,true);return;}if(el){el.textContent=formatTime(left);el.classList.toggle('urgent',left<300000);}},500);}
function leaveExamGuard(){return !(state.examActive&&view.type==='exam')||confirm('Une simulation est en cours. Le chronomètre continuera. Quitter cet écran ?');}
function openChapter(cid,tab='course',highlight=''){view={...view,type:'chapter',chapter:+cid,tab,fcIndex:0,fcFlip:false,qIndex:0,qAnswered:false,highlight};render();}
function startActivity(kind,cid,cids){let scope=cids?.length?cids:(cid?[+cid]:null);if(kind==='course')return openChapter(cid||weakestNotions(1)[0]?.cid||1,'course');if(kind==='ess')return openChapter(cid||weakestNotions(1)[0]?.cid||1,'ess');if(kind==='flash'){view.reviewRefs=dueFlashRefs(30,scope);view.reviewIndex=0;view.reviewFlip=false;view.type='review';return render();}if(kind==='adaptive')return startPractice(scope?.length>1?20:10,scope);if(kind==='errors'){view.type='errors';return render();}if(kind==='exam'){view.type='exam';state.examLast=null;return render();}if(kind==='spanish'){state.settings.lang='es';save();return startPractice(20,scope);}if(kind==='essweak'){let w=weakestNotions(1)[0];return w?openChapter(w.cid,'ess',w.text):render();}}
function bind(){
 $$('[data-go]').forEach(b=>b.onclick=()=>{if(!leaveExamGuard())return;view.type=b.dataset.go;if(view.type!=='exam')state.examLast=null;if(view.type==='review'){view.reviewRefs=[];view.reviewIndex=0;view.reviewFlip=false;}if(view.type==='practice'&&!state.practiceActive)state.practiceLast=null;render();});
 $$('[data-ch]').forEach(b=>{let go=()=>{if(!leaveExamGuard())return;openChapter(+b.dataset.ch,'course')};b.onclick=go;b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go();}}});
 $$('[data-tab]').forEach(b=>b.onclick=()=>{view.tab=b.dataset.tab;view.fcFlip=false;view.qAnswered=false;view.highlight='';render();});
 $('#menu')?.addEventListener('click',()=>$('#side').classList.toggle('open'));
 $('#theme')?.addEventListener('click',()=>{state.settings.dark=!state.settings.dark;save();render();});
 $('#langSelect')?.addEventListener('change',e=>{state.settings.lang=e.target.value;save();view.qIndex=0;render();});
 $('#export')?.addEventListener('click',exportState);$('#import')?.addEventListener('click',importState);
 $$('[data-check]').forEach(x=>x.onchange=()=>{state.checks[x.dataset.check]=x.checked;logActivity('check',{key:x.dataset.check,val:x.checked});render();});
 $('#uncheck')?.addEventListener('click',()=>{chapter(view.chapter).essentials.forEach((_,i)=>delete state.checks[view.chapter+'-'+i]);save();render();});
 $('#flip')?.addEventListener('click',()=>{view.fcFlip=!view.fcFlip;render();});$('#showAnswer')?.addEventListener('click',()=>{view.fcFlip=true;render();});
 $('#prevFc')?.addEventListener('click',()=>{let c=chapter(view.chapter);view.fcIndex=(view.fcIndex-1+c.flashcards.length)%c.flashcards.length;view.fcFlip=false;render();});$('#nextFc')?.addEventListener('click',()=>{let c=chapter(view.chapter);view.fcIndex=(view.fcIndex+1)%c.flashcards.length;view.fcFlip=false;render();});
 $$('[data-rating]').forEach(b=>b.onclick=()=>{let c=chapter(view.chapter),f=pickFlash(c);rateFlash(c.id,f.id,+b.dataset.rating);view.fcIndex=(view.fcIndex+1)%c.flashcards.length;view.fcFlip=false;render();});
 $$('[data-diff]').forEach(b=>b.onclick=()=>{view.qDifficulty=b.dataset.diff;view.qIndex=0;view.qAnswered=false;render();});$('#chapterAdaptive')?.addEventListener('click',()=>startPractice(10,[view.chapter]));
 $$('[data-answer]').forEach(b=>b.onclick=()=>answerQuiz(b.dataset.answer));$('#nextQ')?.addEventListener('click',()=>{let p=poolForChapter(chapter(view.chapter));view.qIndex=(view.qIndex+1)%p.length;view.qAnswered=false;render();});
 $('#reviewFlip')?.addEventListener('click',()=>{view.reviewFlip=!view.reviewFlip;render();});$('#reviewFlipBtn')?.addEventListener('click',()=>{view.reviewFlip=true;render();});$$('[data-review-rating]').forEach(b=>b.onclick=()=>{let ref=view.reviewRefs[view.reviewIndex];rateFlash(ref.cid,ref.fid,+b.dataset.reviewRating);view.reviewRefs.splice(view.reviewIndex,1);view.reviewFlip=false;if(view.reviewIndex>=view.reviewRefs.length)view.reviewIndex=0;render();});
 $('#startAdaptive')?.addEventListener('click',()=>startPractice(10));$$('[data-practice-count]').forEach(b=>b.onclick=()=>startPractice(+b.dataset.practiceCount));$$('[data-practice-answer]').forEach(b=>b.onclick=()=>answerPractice(b.dataset.practiceAnswer));$('#practiceNext')?.addEventListener('click',()=>{let p=state.practiceActive;if(p.index<p.refs.length-1){p.index++;save();render();}else finishPractice();});$('#againAdaptive')?.addEventListener('click',()=>{state.practiceLast=null;save();startPractice(10);});
 $('#clearErrors')?.addEventListener('click',()=>{if(confirm('Effacer tout le carnet d’erreurs ?')){state.errors={};save();render();}});$$('[data-error-course]').forEach(b=>b.onclick=()=>openChapter(+b.dataset.errorCourse,'course',b.dataset.errorTerm||''));$$('[data-error-retest]').forEach(b=>b.onclick=()=>{let [cid,source,id]=b.dataset.errorRetest.split('|');startPractice(1,[+cid],[{cid:+cid,source,qid:id}]);});
 $('#searchForm')?.addEventListener('submit',e=>{e.preventDefault();view.searchQuery=$('#searchInput').value.trim();render();});$$('[data-search-open]').forEach(b=>b.onclick=()=>{let [cid,type,index]=b.dataset.searchOpen.split('|');if(type==='Cours')openChapter(cid,'course',view.searchQuery);else if(type==='Notion')openChapter(cid,'ess',view.searchQuery);else if(type==='Flashcard'){view.fcIndex=+index;openChapter(cid,'flash');}else {view.qIndex=+index;openChapter(cid,'quiz');}});
 $$('[data-plan-mode]').forEach(b=>b.onclick=()=>{view.planMode=b.dataset.planMode;render();});$('#saveTarget')?.addEventListener('click',()=>{let v=$('#targetDate').value;if(v){state.settings.targetDate=v;save();render();}});$('#reflowPlan')?.addEventListener('click',()=>{let r=reflowOverdue();logActivity('plan-reflow',r);if(r.remaining)alert(`${r.moved} séance(s) réorganisée(s). ${r.remaining} n'ont pas pu être replacée(s) avant la date cible.`);render();});$$('[data-plan-done]').forEach(b=>b.onclick=()=>{markPlan(b.dataset.planDone,'done');render();});$$('[data-plan-skip]').forEach(b=>b.onclick=()=>{markPlan(b.dataset.planSkip,'skip');render();});$$('[data-plan-defer]').forEach(b=>b.onclick=()=>{deferPlan(b.dataset.planDefer,1);render();});$$('[data-activity]').forEach(b=>b.onclick=()=>startActivity(b.dataset.activity,b.dataset.cid?+b.dataset.cid:null,b.dataset.cids?b.dataset.cids.split(',').filter(Boolean).map(Number):null));$$('[data-plan-open]').forEach(b=>b.onclick=()=>{view.type='today';render();});
 $$('[data-weak-open]').forEach(b=>b.onclick=()=>{let [cid,i]=b.dataset.weakOpen.split('|');openChapter(+cid,'ess',chapter(+cid).essentials[+i]);});
 $$('[data-exam-count]').forEach(b=>b.onclick=()=>{view.examCount=+b.dataset.examCount;render();});$('#startExam')?.addEventListener('click',()=>startExam(view.examCount));$('#resumeExam')?.addEventListener('click',()=>render());$$('[data-exam-answer]').forEach(b=>b.onclick=()=>{let e=state.examActive;e.answers[e.current]=b.dataset.examAnswer;save();render();});$$('[data-exam-jump]').forEach(b=>b.onclick=()=>{state.examActive.current=+b.dataset.examJump;save();render();});$('#prevExam')?.addEventListener('click',()=>{state.examActive.current=Math.max(0,state.examActive.current-1);save();render();});$('#nextExam')?.addEventListener('click',()=>{let e=state.examActive;if(e.current<e.questions.length-1){e.current++;save();render();}else if(confirm('Tu es à la dernière question. Terminer et afficher le résultat ?'))submitExam(false,true);});$('#markExam')?.addEventListener('click',()=>{let e=state.examActive;e.marked[e.current]=!e.marked[e.current];save();render();});$('#finishExam')?.addEventListener('click',()=>{let e=state.examActive,unanswered=e.questions.length-Object.keys(e.answers||{}).length;if(confirm(`Terminer l’épreuve maintenant ? ${unanswered?unanswered+' question(s) sans réponse.':''}`))submitExam(false,true);});$('#newExam')?.addEventListener('click',()=>{state.examLast=null;save();render();});
}
function answerQuiz(ans){if(view.qAnswered)return;view.qAnswered=true;let c=chapter(view.chapter),p=poolForChapter(c),q=p[view.qIndex],ok=ans===q.answer,order=seededOrder(q,`${c.id}-${qid(q)}-${todayIso()}`);$$('[data-answer]').forEach(b=>{let orig=b.dataset.answer;if(orig===q.answer)b.classList.add('correct');else if(orig===ans)b.classList.add('wrong');b.disabled=true;});let qs=state.quiz[c.id]||{correct:0,total:0};qs.total++;if(ok)qs.correct++;state.quiz[c.id]=qs;recordQuestion(c.id,qid(q),ok);if(ok)resolveError(c.id,qid(q),q._source||'base');else addError(c.id,q,q._source||'base');logActivity('qcm',{cid:c.id,ok});save();let correctDisplay=String.fromCharCode(65+order.indexOf(q.answer));$('#feedback').innerHTML=`<div class="feedback ${ok?'good':'bad'}"><b>${ok?'Bonne réponse.':'À revoir.'}</b> ${esc(questionWhy(q))}${!ok?`<br><small>Bonne réponse affichée : ${correctDisplay}. ${esc(answerText(q,q.answer))}</small><div class="feedback-actions"><button class="btn" data-error-course="${c.id}" data-error-term="${esc(tokens(q.q)[0]||'')}">Revoir dans le cours</button><button class="btn" id="quickRetest">Retester plus tard</button></div>`:''}</div>`;$('#nextQ').disabled=false;$('#feedback [data-error-course]')?.addEventListener('click',e=>openChapter(c.id,'course',e.currentTarget.dataset.errorTerm||''));$('#quickRetest')?.addEventListener('click',()=>{addError(c.id,q,q._source||'base');save();});}
function answerPractice(ans){let p=state.practiceActive;if(!p||p.answers[p.index])return;let ref=p.refs[p.index],{q}=getRef(ref);if(!q)return;let ok=ans===q.answer;p.answers[p.index]=ans;recordQuestion(ref.cid,qid(q),ok);if(ok){p.correct++;resolveError(ref.cid,qid(q),ref.source);}else addError(ref.cid,q,ref.source);logActivity('qcm-adaptive',{cid:ref.cid,ok});save();render();}
function exportState(){let payload={app:'UAX Biologie',version:'3.1',exportedAt:new Date().toISOString(),state},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`progression-uax-biologie-v3-1-${todayIso()}.json`;a.click();URL.revokeObjectURL(a.href);}
function importState(){let back=document.createElement('div');back.className='modal-back';back.innerHTML='<div class="modal"><h3>Importer une progression</h3><p>Collez le JSON exporté depuis une version précédente ou la V3.</p><textarea id="impText"></textarea><div class="flash-controls" style="justify-content:flex-end"><button class="btn" id="cancelImp">Annuler</button><button class="btn primary" id="okImp">Importer</button></div></div>';document.body.appendChild(back);$('#cancelImp').onclick=()=>back.remove();$('#okImp').onclick=()=>{try{let obj=JSON.parse($('#impText').value),incoming=obj.state||obj;state=Object.assign(blank(),incoming);state.settings=Object.assign(blank().settings,incoming.settings||{});save();back.remove();render();}catch(e){alert('JSON invalide.');}};}

document.addEventListener('keydown',e=>{let tag=(e.target?.tagName||'').toLowerCase();if(['input','textarea','select'].includes(tag))return;if(e.key==='Escape')$('#side')?.classList.remove('open');let k=e.key.toUpperCase();if(['A','B','C','D'].includes(k)){let b=$(`[data-shortcut="${k}"]:not([disabled])`);if(b){e.preventDefault();b.click();return;}}if(e.code==='Space'&&(view.type==='review'||(view.type==='chapter'&&view.tab==='flash'))){e.preventDefault();(view.type==='review'?$('#reviewFlip'):$('#flip'))?.click();}if(view.type==='exam'&&state.examActive){if(e.key==='ArrowRight')$('#nextExam')?.click();if(e.key==='ArrowLeft')$('#prevExam')?.click();}});

save();render();
})();
